# Datenbank-Verbindung
#alt: spring.datasource.url=jdbc:mysql://178.63.60.92:31337/schulprojekt?sslMode=VERIFY_CA&enabledTLSProtocols=TLSv1.2,TLSv1.3&serverTimezone=UTC
spring.datasource.url=jdbc:mysql://178.63.60.92:31337/schulprojekt?sslMode=VERIFY_CA&enabledTLSProtocols=TLSv1.2,TLSv1.3&serverTimezone=UTC
spring.datasource.username=schulprojekt
spring.datasource.password=${OPENSHIFT_MYSQL_DB_PASSWORD}

spring.datasource.hikari.data-source-properties.trustCertificateKeyStoreUrl=file:src/main/resources/ssl/truststore.jks
spring.datasource.hikari.data-source-properties.trustCertificateKeyStorePassword=aM4i3lPM!
spring.datasource.hikari.data-source-properties.trustCertificateKeyStoreType=JKS

# Hibernate
spring.jpa.hibernate.ddl-auto=none
# spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
# in SpringBoot am besten keinen Dialekt setzen

spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.default_batch_fetch_size=50

management.endpoints.web.exposure.include=health,info,beans,env,configprops
management.endpoint.health.show-details=always

# Datenbankstruktur bearbeiten. NUR BEI MAIKE AUSFUEHRBAR
# spring.sql.init.mode=always
# spring.sql.init.encoding=UTF-8
# spring.jpa.defer-datasource-initialization=true

# Datenbank fuellen NUR BEI MAIKE AUSFUEHRBAR
# spring.sql.init.mode=always
# spring.sql.init.data-locations=classpath:data.sql
# spring.jpa.defer-datasource-initialization=true
